### ISSUE TITLE
Find a more generic name

### ISSUE THREAD

**Issue by cburgdorf** [ninya-io/ninya.io#25]
The current name is quite bound to StackOverflow. I like to push this project into a direction where it includes users from other interesting platforms as well (e.g dribble or github).

Therefore I want to find a better suited name.

I was looking at domain availability and unfortunately _ninja.io_, _nerds.io_ are already taken.

Here is a list of free candidates:

elves.io
ninya.io
ninyas.io
ninyaz.io

**Comment by 0x-r4bbit** [comment]
would go for ninyas.io instead of ninya.io

**Comment by cburgdorf** [comment]
How about ninyaz.io? But I somehow consider ninya.io a bit cleaner ;-)

**Comment by 0x-r4bbit** [comment]
You could combine a cat with it, I think (can haz ninyaz?)

**Comment by cburgdorf** [comment]
I'll go with ninya.io. Already blocked the domain :)

**Comment by 0x-r4bbit** [comment]
allright.

On Sun, Mar 2, 2014 at 2:00 PM, Christoph Burgdorf <notifications@github.com

> wrote:
> 
> Closed #25 https://github.com/cburgdorf/StackWho/issues/25.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cburgdorf/StackWho/issues/25
> .

## 

/pp

**Comment by dandv** [comment]
I actually liked StackWho, but I understand it was generic.

**Comment by dandv** [comment]
ninya.io doesn't point to the Heroku app yet?

**Comment by cburgdorf** [comment]
There's a problem with leaving out `www` that I need to fix. www.ninyia.io works though.
