### ISSUE TITLE
Spice up the result view

### ISSUE THREAD

**Issue by cburgdorf** [ninya-io/ninya.io#6]
The whole search result needs to look nicer and in addition we should also show more information:
- [x] the top 30 tags of the user with the tags from the search highlighted
- [x] the picture of the user
- [ ] the top answers related to the tags from the search

**Comment by cburgdorf** [comment]
We have the last point covered in it's own ticket.

**Comment by oriSomething** [comment]
top answers: maybe in the addition information? (card flip (-;)

**Comment by cburgdorf** [comment]
we have a separate ticket for that here https://github.com/ninya-io/ninya.io/issues/31
